# Generated by Django 5.0.1 on 2024-01-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
            ],
        ),
    ]
